### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-1-Don** [UMSF-K13-1-Don/K13-1-Don-MyProject#1]
загрузила проект в хранилище(так как не получилось через VS2010, сделала на прямую)
![image](https://cloud.githubusercontent.com/assets/19637086/15707375/1b7caf70-2801-11e6-9721-026c8fcbda87.png)
результат комита
![image](https://cloud.githubusercontent.com/assets/19637086/15707385/2e338012-2801-11e6-9818-cd7a9d41ad63.png)

**Comment by Smoktii** [comment]
Ок
